/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __defProps = Object.defineProperties;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
__export(exports, {
  default: () => SmartLinkFormatterPlugin
});
var import_obsidian5 = __toModule(require("obsidian"));

// src/settings.ts
var import_obsidian4 = __toModule(require("obsidian"));

// src/clients.ts
var import_obsidian2 = __toModule(require("obsidian"));

// src/utils.ts
var MARKDOWN_LINK_REGEX = /\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g;
var URL_REGEX = /https?:\/\/[^\s)]+/g;
function escapeMarkdownChars(text) {
  return text.replace(/([[\]|*_`\\])/g, "\\$1");
}
function applyTitleReplacements(text, replacements) {
  let result = text;
  for (const { pattern, replacement, enabled } of replacements) {
    if (!enabled || !pattern)
      continue;
    try {
      const regex = new RegExp(pattern, "g");
      result = result.replace(regex, replacement);
    } catch (e) {
      console.error(`Invalid replacement pattern "${pattern}":`, e);
    }
  }
  return result.trim();
}
function unescapeHtml(text) {
  const map = {
    "&amp;": "&",
    "&lt;": "<",
    "&gt;": ">",
    "&quot;": '"',
    "&#39;": "'"
  };
  return text.replace(/&amp;|&lt;|&gt;|&quot;|&#39;/g, (m) => map[m]).replace(/&#(\d+);/g, (_, dec) => String.fromCharCode(Number(dec))).replace(/&#x([0-9a-f]+);/gi, (_, hex) => String.fromCharCode(parseInt(hex, 16)));
}
function isLink(text) {
  return !!text.trim().match(/^https?:\/\/\S+$/);
}
function normalizeUrl(url) {
  return url.replace(/^https?:\/\/(www\.)?/, "https://");
}
function isPositionProtected(allLines, lineNum, ch) {
  const line = allLines[lineNum];
  const textBefore = line.substring(0, ch);
  const backticksBefore = (textBefore.match(/`/g) || []).length;
  if (backticksBefore % 2 === 1)
    return true;
  const charBefore = ch > 0 ? line[ch - 1] : "";
  const charAfter = ch < line.length ? line[ch] : "";
  if (charBefore === "`" || charAfter === "`")
    return true;
  let inCodeBlock = false;
  for (let i = 0; i < lineNum; i++) {
    if (allLines[i].trim().startsWith("```")) {
      inCodeBlock = !inCodeBlock;
    }
  }
  if (inCodeBlock)
    return true;
  if (lineNum === 0 && line.trim() === "---")
    return true;
  if (lineNum > 0 && allLines[0].trim() === "---") {
    let inFrontmatter = true;
    for (let i = 1; i <= lineNum; i++) {
      if (allLines[i].trim() === "---") {
        inFrontmatter = false;
        break;
      }
    }
    if (inFrontmatter)
      return true;
  }
  const fullTextBefore = allLines.slice(0, lineNum).join("\n") + "\n" + textBefore;
  const openComments = (fullTextBefore.match(/<!--/g) || []).length;
  const closeComments = (fullTextBefore.match(/-->/g) || []).length;
  if (openComments > closeComments)
    return true;
  return false;
}
function findUnformattedUrls(allLines, startLine, endLine) {
  URL_REGEX.lastIndex = 0;
  const results = [];
  for (let lineNum = startLine; lineNum <= endLine; lineNum++) {
    const line = allLines[lineNum];
    const markdownRanges = [];
    MARKDOWN_LINK_REGEX.lastIndex = 0;
    let mdMatch;
    while ((mdMatch = MARKDOWN_LINK_REGEX.exec(line)) !== null) {
      markdownRanges.push({ start: mdMatch.index, end: mdMatch.index + mdMatch[0].length });
    }
    URL_REGEX.lastIndex = 0;
    let urlMatch;
    while ((urlMatch = URL_REGEX.exec(line)) !== null) {
      const start = urlMatch.index;
      const end = start + urlMatch[0].length;
      if (markdownRanges.some((r) => start >= r.start && end <= r.end))
        continue;
      if (isPositionProtected(allLines, lineNum, start))
        continue;
      results.push({ url: urlMatch[0], line: lineNum, start, end });
    }
  }
  return results;
}
function extractMarkdownLink(line, cursorCh) {
  MARKDOWN_LINK_REGEX.lastIndex = 0;
  let match;
  while ((match = MARKDOWN_LINK_REGEX.exec(line)) !== null) {
    const start = match.index;
    const end = start + match[0].length;
    if (cursorCh >= start && cursorCh <= end) {
      return {
        url: match[2],
        start,
        end
      };
    }
  }
  return null;
}
function extractPlainUrl(line, cursorCh) {
  URL_REGEX.lastIndex = 0;
  let match;
  while ((match = URL_REGEX.exec(line)) !== null) {
    const start = match.index;
    const end = start + match[0].length;
    if (cursorCh >= start && cursorCh <= end) {
      return {
        url: match[0],
        start,
        end
      };
    }
  }
  return null;
}
function extractUrlAtCursor(line, cursorCh) {
  var _a;
  return (_a = extractMarkdownLink(line, cursorCh)) != null ? _a : extractPlainUrl(line, cursorCh);
}
function formatDuration(totalSeconds) {
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor(totalSeconds % 3600 / 60);
  const seconds = totalSeconds % 60;
  const parts = [];
  if (hours > 0)
    parts.push(hours.toString());
  parts.push(minutes.toString().padStart(hours > 0 ? 2 : 1, "0"));
  parts.push(seconds.toString().padStart(2, "0"));
  return parts.join(":");
}

// src/title-utils.ts
var import_obsidian = __toModule(require("obsidian"));
function blank(text) {
  return text === void 0 || text === null || text === "";
}
function generateUniqueToken(url) {
  const id = `link-placeholder-${Date.now()}_${Math.floor(Math.random() * 1e6)}`;
  return `<span class="link-loading" id="${id}" ${url ? `url="${url}"` : ""}>Loading...</span>`;
}
function getUrlFinalSegment(url) {
  try {
    const urlObject = new URL(url);
    const segments = urlObject.pathname.split("/");
    const nonEmptySegments = segments.filter((segment) => segment.length > 0);
    const last = nonEmptySegments.pop();
    return last || "File";
  } catch (e) {
    return url;
  }
}
function loadElectronWindow(window2, url) {
  return __async(this, null, function* () {
    return new Promise((resolve, reject) => {
      const timer = window2.setTimeout(() => {
        console.warn(`Smart Link Formatter: Timeout loading ${url} in Electron window.`);
        try {
          if (window2 && !window2.isDestroyed()) {
            window2.webContents.stop();
          }
        } catch (e) {
        }
        reject(new Error(`Timeout loading URL: ${url}`));
      }, 3e4);
      const didFinishLoad = () => {
        window2.clearTimeout(timer);
        window2.webContents.removeListener("did-finish-load", didFinishLoad);
        window2.webContents.removeListener("did-fail-load", didFailLoad);
        resolve();
      };
      const didFailLoad = (event, errorCode, errorDescription, validatedURL, isMainFrame) => {
        window2.clearTimeout(timer);
        if (isMainFrame === false) {
          console.debug(`Smart Link Formatter: Non-main frame load failed for ${validatedURL}: ${errorDescription}. Continuing for main frame.`);
          return;
        }
        window2.webContents.removeListener("did-finish-load", didFinishLoad);
        window2.webContents.removeListener("did-fail-load", didFailLoad);
        reject(new Error(`Failed to load URL: ${validatedURL} - ${errorDescription} (Code: ${errorCode})`));
      };
      window2.webContents.on("did-finish-load", didFinishLoad);
      window2.webContents.on("did-fail-load", didFailLoad);
      window2.loadURL(url);
    });
  });
}
function electronGetPageTitle(url) {
  return __async(this, null, function* () {
    if (import_obsidian.Platform.isMobile) {
      console.warn("Smart Link Formatter: Electron not available on mobile platform.");
      return null;
    }
    let electronPkg;
    try {
      electronPkg = require("electron");
    } catch (e) {
      console.warn("Smart Link Formatter: Electron module not available.");
      return null;
    }
    if (!electronPkg || !electronPkg.remote) {
      console.warn("Smart Link Formatter: Electron remote module not available for electronGetPageTitle.");
      return null;
    }
    const { BrowserWindow } = electronPkg.remote;
    let window2 = null;
    try {
      window2 = new BrowserWindow({
        width: 1e3,
        height: 600,
        webPreferences: {
          webSecurity: true,
          nodeIntegration: false,
          contextIsolation: true,
          images: false,
          javascript: true
        },
        show: false
      });
      window2.webContents.setAudioMuted(true);
      yield loadElectronWindow(window2, url);
      const title = window2.webContents.getTitle();
      return !blank(title) ? title : null;
    } catch (ex) {
      console.error(`Smart Link Formatter: Error in electronGetPageTitle for ${url}:`, ex);
      return null;
    } finally {
      if (window2 && !window2.isDestroyed()) {
        window2.destroy();
      }
    }
  });
}
function fetchTitleWithRequestUrl(urlToFetch) {
  return __async(this, null, function* () {
    var _a, _b, _c, _d, _e;
    try {
      const response = yield (0, import_obsidian.requestUrl)({ url: urlToFetch, method: "GET" });
      const contentType = (_a = response.headers["content-type"]) == null ? void 0 : _a.toLowerCase();
      if (contentType && !contentType.includes("text/html")) {
        return getUrlFinalSegment(urlToFetch) || urlToFetch;
      }
      const text = response.text;
      const doc = new DOMParser().parseFromString(text, "text/html");
      const titleElement = doc.querySelector("title");
      const actualTitle = (_b = titleElement == null ? void 0 : titleElement.innerText) == null ? void 0 : _b.trim();
      if (!blank(actualTitle)) {
        return actualTitle;
      }
      const noTitleAttr = (_c = titleElement == null ? void 0 : titleElement.getAttribute("no-title")) == null ? void 0 : _c.trim();
      if (!blank(noTitleAttr)) {
        return noTitleAttr;
      }
      const h1Element = doc.querySelector("h1");
      const h1Text = (_d = h1Element == null ? void 0 : h1Element.innerText) == null ? void 0 : _d.trim();
      if (!blank(h1Text)) {
        return h1Text;
      }
      const metaTitleElement = doc.querySelector('meta[property="og:title"], meta[name="twitter:title"], meta[itemprop="name"]');
      const metaTitleContent = (_e = metaTitleElement == null ? void 0 : metaTitleElement.getAttribute("content")) == null ? void 0 : _e.trim();
      if (!blank(metaTitleContent)) {
        return metaTitleContent;
      }
      return urlToFetch;
    } catch (error) {
      console.error(`Smart Link Formatter: Failed to fetch page title via requestUrl for ${urlToFetch}:`, error);
      return urlToFetch;
    }
  });
}
function tryGetContentTypeAndSegment(url) {
  return __async(this, null, function* () {
    var _a;
    try {
      const response = yield (0, import_obsidian.requestUrl)({ url, method: "HEAD" });
      const contentType = (_a = response.headers["content-type"]) == null ? void 0 : _a.toLowerCase();
      if (contentType && !contentType.includes("text/html")) {
        return getUrlFinalSegment(url) || url;
      }
      return null;
    } catch (err) {
      console.warn(`Smart Link Formatter: HEAD request for ${url} failed or inconclusive. Proceeding with GET. Error:`, err);
      return null;
    }
  });
}
function getPageTitleOrchestrator(url) {
  return __async(this, null, function* () {
    let processedUrl = url;
    if (!(processedUrl.startsWith("http") || processedUrl.startsWith("https"))) {
      processedUrl = "https://" + processedUrl;
    }
    let title = null;
    const nonHtmlTitle = yield tryGetContentTypeAndSegment(processedUrl);
    if (nonHtmlTitle) {
      return escapeMarkdownChars(nonHtmlTitle);
    }
    if (import_obsidian.Platform.isMobile) {
      title = yield fetchTitleWithRequestUrl(processedUrl);
    } else {
      try {
        title = yield electronGetPageTitle(processedUrl);
      } catch (electronError) {
        console.error(`Smart Link Formatter: electronGetPageTitle failed for ${processedUrl}:`, electronError);
        title = null;
      }
      if (blank(title)) {
        title = yield fetchTitleWithRequestUrl(processedUrl);
      }
    }
    return escapeMarkdownChars(title || processedUrl);
  });
}

// src/clients.ts
var import_obsidian3 = __toModule(require("obsidian"));
var Client = class {
  format(metadata, url, plugin) {
    var _a;
    const template = ((_a = plugin.settings.clientFormats) == null ? void 0 : _a[this.name]) || this.defaultFormat;
    let formattedText = formatTemplate(template, metadata, url);
    if (plugin.settings.titleReplacements.length > 0) {
      formattedText = applyTitleReplacements(formattedText, plugin.settings.titleReplacements);
    }
    return wrapInMarkdownLink(formattedText, url);
  }
};
function formatTemplate(template, metadata, url) {
  let result = template;
  let previousResult = "";
  while (result !== previousResult) {
    previousResult = result;
    result = result.replace(/{([^{}]+?)}/g, (match, key) => {
      const conditionalMatch = key.match(/^([^?|]+)\?(.*)$/);
      if (conditionalMatch) {
        const fieldName = conditionalMatch[1].trim();
        const branches = conditionalMatch[2];
        const fieldValue = fieldName === "url" ? url : metadata[fieldName];
        const isPresent = fieldValue !== void 0 && fieldValue !== "";
        if (!isPresent) {
          for (let i = 1; i < branches.length; i++) {
            if (branches[i] === ":" && branches[i - 1] !== "\\") {
              return branches.substring(i + 1).replace(/\\:/g, ":");
            }
          }
          return "";
        }
        for (let i = 1; i < branches.length; i++) {
          if (branches[i] === ":" && branches[i - 1] !== "\\") {
            return branches.substring(0, i).replace(/\\:/g, ":");
          }
        }
        return branches.replace(/\\:/g, ":");
      }
      const [variable, format] = key.split("|").map((s) => s.trim());
      if (variable === "url") {
        return url;
      }
      const value = metadata[variable];
      if (value === void 0) {
        return "";
      }
      const dateFields = ["upload_date", "created_at"];
      if (format && dateFields.includes(variable) && (0, import_obsidian3.moment)(value).isValid()) {
        return (0, import_obsidian3.moment)(value).format(format);
      }
      return String(value);
    });
  }
  return result;
}
function wrapInMarkdownLink(formattedText, url) {
  const isEmbed = formattedText.startsWith("!");
  const textToProcess = isEmbed ? formattedText.substring(1) : formattedText;
  let link;
  const linkMatch = textToProcess.match(/(?<!\\)\[(.*?)(?<!\\)\]/);
  if (linkMatch && linkMatch[1]) {
    const linkContent = linkMatch[1];
    const firstBracketIndex = textToProcess.indexOf(linkMatch[0]);
    const suffix = textToProcess.slice(firstBracketIndex + linkMatch[0].length);
    link = `[${linkContent}](${url})${suffix}`;
  } else {
    link = textToProcess.trim();
  }
  return isEmbed ? `!${link}` : link;
}
var YouTubeClient = class extends Client {
  constructor() {
    super(...arguments);
    this.name = "youtube";
    this.displayName = "YouTube";
    this.defaultFormat = "[{title}] by {channel}";
    this.matches = (url) => {
      if (url.match(/^https:\/\/(youtube\.com|youtu\.be)\//)) {
        return true;
      }
      return false;
    };
  }
  getAvailableVariables() {
    return [
      "title",
      "channel",
      "uploader",
      "duration",
      "views",
      "upload_date",
      "description",
      "url",
      "timestamp"
    ];
  }
  fetchMetadata(url) {
    return __async(this, null, function* () {
      var _a, _b, _c, _d;
      const response = yield (0, import_obsidian2.requestUrl)({ url, method: "GET" });
      const html = response.text;
      const match = html.match(/var ytInitialPlayerResponse = ({.*?});/);
      const dataMatch = html.match(/var ytInitialData = ({.*?});/);
      let playerResponseJson = null;
      if (match && match[1]) {
        playerResponseJson = JSON.parse(match[1]);
      } else if (dataMatch && dataMatch[1]) {
        playerResponseJson = JSON.parse(dataMatch[1]);
      } else {
        throw new Error("Could not find ytInitialPlayerResponse or ytInitialData in HTML.");
      }
      const videoDetails = playerResponseJson.videoDetails;
      const microformat = (_a = playerResponseJson.microformat) == null ? void 0 : _a.playerMicroformatRenderer;
      if (!videoDetails && !microformat) {
        throw new Error("Could not find videoDetails or microformat in JSON data.");
      }
      const title = (videoDetails == null ? void 0 : videoDetails.title) || ((_b = microformat == null ? void 0 : microformat.title) == null ? void 0 : _b.simpleText);
      const uploader = (videoDetails == null ? void 0 : videoDetails.author) || ((_c = microformat == null ? void 0 : microformat.ownerChannelName) == null ? void 0 : _c.simpleText);
      const description = (videoDetails == null ? void 0 : videoDetails.shortDescription) || ((_d = microformat == null ? void 0 : microformat.description) == null ? void 0 : _d.simpleText);
      const views = videoDetails == null ? void 0 : videoDetails.viewCount;
      const durationSeconds = videoDetails == null ? void 0 : videoDetails.lengthSeconds;
      const uploadDate = microformat == null ? void 0 : microformat.publishDate;
      return {
        title: title ? escapeMarkdownChars(title) : void 0,
        uploader: uploader ? escapeMarkdownChars(uploader) : void 0,
        channel: uploader ? escapeMarkdownChars(uploader) : void 0,
        description: description ? escapeMarkdownChars(description) : void 0,
        views: views ? parseInt(views).toLocaleString() : void 0,
        duration: durationSeconds ? formatDuration(parseInt(durationSeconds)) : void 0,
        upload_date: uploadDate ? escapeMarkdownChars(uploadDate) : void 0
      };
    });
  }
  format(metadata, url, plugin) {
    const urlObj = new URL(url);
    const seconds = this.getYouTubeTimestamp(urlObj);
    let timestampStr = "";
    if (seconds) {
      const hours = Math.floor(seconds / 3600);
      const mins = Math.floor(seconds % 3600 / 60);
      const secs = seconds % 60;
      timestampStr = hours > 0 ? `@${hours}:${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}` : `@${mins}:${secs.toString().padStart(2, "0")}`;
    }
    const extendedMetadata = __spreadProps(__spreadValues({}, metadata), { timestamp: timestampStr });
    return super.format(extendedMetadata, url, plugin);
  }
  getYouTubeTimestamp(url) {
    let timestamp = url.searchParams.get("t") || url.searchParams.get("time_continue") || "";
    timestamp = timestamp.replace("s", "");
    return Number(timestamp);
  }
};
var YouTubeMusicClient = class extends Client {
  constructor() {
    super(...arguments);
    this.name = "youtube-music";
    this.displayName = "YouTube Music";
    this.defaultFormat = "[{title}] - {artist}";
    this.matches = (url) => {
      return url.match(/^https:\/\/music\.youtube\.com\//) !== null;
    };
  }
  getAvailableVariables() {
    return ["title", "artist", "duration", "views", "url"];
  }
  fetchMetadata(url) {
    return __async(this, null, function* () {
      const videoId = this.extractVideoId(url);
      if (!videoId) {
        throw new Error("Could not extract video ID from URL");
      }
      const payload = {
        videoId,
        context: {
          client: {
            clientName: "WEB_REMIX",
            clientVersion: "1.20251015.03.00",
            hl: "en",
            gl: "US"
          }
        }
      };
      const response = yield (0, import_obsidian2.requestUrl)({
        url: "https://music.youtube.com/youtubei/v1/player?prettyPrint=false",
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(payload)
      });
      const data = JSON.parse(response.text);
      const videoDetails = data.videoDetails;
      if (!videoDetails) {
        throw new Error("Could not find videoDetails in response");
      }
      return {
        title: videoDetails.title ? escapeMarkdownChars(videoDetails.title) : void 0,
        artist: videoDetails.author ? escapeMarkdownChars(videoDetails.author) : void 0,
        duration: videoDetails.lengthSeconds ? formatDuration(parseInt(videoDetails.lengthSeconds)) : void 0,
        views: videoDetails.viewCount ? parseInt(videoDetails.viewCount).toLocaleString() : void 0
      };
    });
  }
  extractVideoId(url) {
    const urlObj = new URL(url);
    return urlObj.searchParams.get("v");
  }
};
var ImageClient = class extends Client {
  constructor() {
    super(...arguments);
    this.name = "image";
    this.displayName = "Image";
    this.defaultFormat = "![{title}]";
    this.matches = (url) => {
      return url.match(/\.(jpg|jpeg|png|gif|bmp|tiff|ico|webp|svg|heic|heif)$/i) !== null;
    };
  }
  getAvailableVariables() {
    return ["title", "url"];
  }
  fetchMetadata(url) {
    return __async(this, null, function* () {
      const filename = url.substring(url.lastIndexOf("/") + 1);
      return {
        title: filename ? escapeMarkdownChars(decodeURIComponent(filename)) : "image"
      };
    });
  }
};
var TwitterClient = class extends Client {
  constructor() {
    super(...arguments);
    this.name = "twitter";
    this.displayName = "Twitter/X";
    this.defaultFormat = "[{text}] - @{author}";
    this.queryId = null;
    this.bearerToken = null;
    this.features = null;
    this.fieldToggles = null;
    this.matches = (url) => {
      return /^https:\/\/(twitter\.com|x\.com)\/\w+\/status\/\d+/.test(url);
    };
  }
  getAvailableVariables() {
    return ["text", "author", "name", "likes", "retweets", "replies", "views", "created_at", "url"];
  }
  loadTwitterAPIConfig() {
    return __async(this, null, function* () {
      var _a;
      try {
        const graphqlResponse = yield (0, import_obsidian2.requestUrl)({
          url: "https://raw.githubusercontent.com/fa0311/TwitterInternalAPIDocument/master/docs/json/GraphQL.json",
          method: "GET"
        });
        const graphqlData = JSON.parse(graphqlResponse.text);
        const endpoint = graphqlData.find((item) => {
          var _a2;
          return ((_a2 = item.exports) == null ? void 0 : _a2.operationName) === "TweetResultByRestId";
        });
        if (endpoint) {
          this.queryId = endpoint.exports.queryId;
          const metadata = endpoint.exports.metadata;
          if (metadata) {
            if (metadata.featureSwitch) {
              this.features = {};
              for (const [key, val] of Object.entries(metadata.featureSwitch)) {
                const value = val.value;
                this.features[key] = value === "true" ? true : value === "false" ? false : value;
              }
            }
            if (metadata.fieldToggles) {
              this.fieldToggles = {};
              for (const toggle of metadata.fieldToggles) {
                this.fieldToggles[toggle] = true;
              }
            }
          }
        }
        const apiResponse = yield (0, import_obsidian2.requestUrl)({
          url: "https://raw.githubusercontent.com/fa0311/TwitterInternalAPIDocument/master/docs/deck/json/API.json",
          method: "GET"
        });
        const apiData = JSON.parse(apiResponse.text);
        this.bearerToken = (_a = apiData.header) == null ? void 0 : _a.authorization;
      } catch (error) {
        console.error("Failed to load Twitter API config from GitHub:", error);
        this.queryId = "jGOLj4UQ6l5z9uUKfhqEHA";
        this.bearerToken = "Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA";
      }
    });
  }
  getGuestToken() {
    return __async(this, null, function* () {
      if (!this.bearerToken) {
        yield this.loadTwitterAPIConfig();
      }
      const response = yield (0, import_obsidian2.requestUrl)({
        url: "https://api.x.com/1.1/guest/activate.json",
        method: "POST",
        headers: {
          "authorization": this.bearerToken
        }
      });
      const data = JSON.parse(response.text);
      return data.guest_token;
    });
  }
  fetchMetadata(url) {
    return __async(this, null, function* () {
      var _a, _b, _c;
      if (!this.queryId || !this.bearerToken) {
        yield this.loadTwitterAPIConfig();
      }
      const tweetId = this.extractTweetId(url);
      if (!tweetId) {
        throw new Error("Could not extract tweet ID from URL");
      }
      const guestToken = yield this.getGuestToken();
      const variables = {
        tweetId,
        withCommunity: false,
        includePromotedContent: false,
        withVoice: false
      };
      const apiUrl = `https://x.com/i/api/graphql/${this.queryId}/TweetResultByRestId?variables=${encodeURIComponent(JSON.stringify(variables))}&features=${encodeURIComponent(JSON.stringify(this.features))}&fieldToggles=${encodeURIComponent(JSON.stringify(this.fieldToggles))}`;
      const response = yield (0, import_obsidian2.requestUrl)({
        url: apiUrl,
        method: "GET",
        headers: {
          "authorization": this.bearerToken,
          "x-guest-token": guestToken,
          "x-twitter-active-user": "yes",
          "x-twitter-client-language": "en"
        }
      });
      const data = JSON.parse(response.text);
      const result = (_b = (_a = data == null ? void 0 : data.data) == null ? void 0 : _a.tweetResult) == null ? void 0 : _b.result;
      if (!result) {
        throw new Error("Tweet result not found");
      }
      const legacy = result.legacy;
      const username = result.core.user_results.result.core.screen_name;
      const authorName = result.core.user_results.result.core.name;
      return {
        text: (legacy == null ? void 0 : legacy.full_text) ? escapeMarkdownChars(legacy.full_text) : void 0,
        author: username ? escapeMarkdownChars(username) : void 0,
        name: authorName ? escapeMarkdownChars(authorName) : void 0,
        likes: legacy == null ? void 0 : legacy.favorite_count,
        retweets: legacy == null ? void 0 : legacy.retweet_count,
        replies: legacy == null ? void 0 : legacy.reply_count,
        views: ((_c = result.views) == null ? void 0 : _c.count) ? parseInt(result.views.count).toLocaleString() : void 0,
        created_at: (legacy == null ? void 0 : legacy.created_at) ? escapeMarkdownChars(legacy.created_at) : void 0
      };
    });
  }
  extractTweetId(url) {
    const match = url.match(/status\/(\d+)/);
    return match ? match[1] : null;
  }
};
var RedditClient = class extends Client {
  constructor() {
    super(...arguments);
    this.name = "reddit";
    this.displayName = "Reddit";
    this.defaultFormat = "[{title}] - r/{subreddit}";
    this.matches = (url) => {
      return /^https:\/\/reddit\.com\/r\/[\w-]+\/comments\//.test(url);
    };
  }
  getAvailableVariables() {
    return ["title", "subreddit", "author", "upvotes", "comments", "created_at", "url"];
  }
  fetchMetadata(url) {
    return __async(this, null, function* () {
      var _a, _b, _c, _d;
      const jsonUrl = url.replace(/\/$/, "") + ".json";
      const response = yield (0, import_obsidian2.requestUrl)({
        url: jsonUrl,
        method: "GET",
        headers: {
          "User-Agent": "Obsidian Smart Link Formatter"
        }
      });
      const data = JSON.parse(response.text);
      const postData = (_d = (_c = (_b = (_a = data[0]) == null ? void 0 : _a.data) == null ? void 0 : _b.children) == null ? void 0 : _c[0]) == null ? void 0 : _d.data;
      if (!postData) {
        throw new Error("Could not find post data");
      }
      return {
        title: postData.title ? escapeMarkdownChars(postData.title) : void 0,
        subreddit: postData.subreddit ? escapeMarkdownChars(postData.subreddit) : void 0,
        author: postData.author ? escapeMarkdownChars(postData.author) : void 0,
        upvotes: postData.ups ? postData.ups.toLocaleString() : void 0,
        comments: postData.num_comments ? postData.num_comments.toLocaleString() : void 0,
        created_at: postData.created_utc ? new Date(postData.created_utc * 1e3).toISOString() : void 0
      };
    });
  }
};
var GitHubClient = class extends Client {
  constructor() {
    super(...arguments);
    this.name = "github";
    this.displayName = "GitHub";
    this.defaultFormat = "[{owner}/{repo}]: {description}";
    this.matches = (url) => {
      return /^https:\/\/github\.com\/[\w-]+\/[\w-]+(\/)?$/.test(url);
    };
  }
  getAvailableVariables() {
    return ["owner", "repo", "description"];
  }
  fetchMetadata(url) {
    return __async(this, null, function* () {
      const response = yield (0, import_obsidian2.requestUrl)({ url, method: "GET" });
      const html = response.text;
      const titleMatch = html.match(/<meta property="og:title" content="([^"]+)"/);
      const fullRepoName = titleMatch == null ? void 0 : titleMatch[1];
      let owner, repo, description;
      if (fullRepoName) {
        [owner, repo] = fullRepoName.split("/");
        [repo, description] = repo.split(": ");
        owner = owner.split("- ")[1];
      }
      return {
        owner: owner ? escapeMarkdownChars(owner) : void 0,
        repo: repo ? escapeMarkdownChars(repo) : void 0,
        description: description ? escapeMarkdownChars(description) : void 0
      };
    });
  }
};
var DefaultClient = class extends Client {
  constructor() {
    super(...arguments);
    this.name = "default";
    this.displayName = "Default";
    this.defaultFormat = "[{title}]";
  }
  getAvailableVariables() {
    return ["title", "url"];
  }
  fetchMetadata(url) {
    return __async(this, null, function* () {
      const title = yield getPageTitleOrchestrator(url);
      return { title };
    });
  }
  matches() {
    return true;
  }
};
var CLIENTS = [
  new YouTubeClient(),
  new YouTubeMusicClient(),
  new ImageClient(),
  new TwitterClient(),
  new RedditClient(),
  new GitHubClient(),
  new DefaultClient()
];

// src/types/failure-mode.ts
var FailureMode;
(function(FailureMode2) {
  FailureMode2["Alert"] = "alert";
  FailureMode2["Revert"] = "revert";
})(FailureMode || (FailureMode = {}));
(function(FailureMode2) {
  function format(mode, text) {
    if (mode === FailureMode2.Alert) {
      return `[Failed to fetch title](${text})`;
    } else {
      return text;
    }
  }
  FailureMode2.format = format;
})(FailureMode || (FailureMode = {}));

// src/settings.ts
var DEFAULT_SETTINGS = {
  autoLink: true,
  pasteIntoSelection: false,
  failureMode: FailureMode.Revert,
  timeoutSeconds: 10,
  blacklistedDomains: "",
  titleReplacements: [],
  clientFormats: {}
};
var LinkFormatterSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.activeSection = "general";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const navContainer = containerEl.createDiv("smart-link-formatter-nav");
    const generalTab = navContainer.createEl("button", {
      text: "General",
      cls: this.activeSection === "general" ? "smart-link-formatter-tab-active" : ""
    });
    generalTab.onclick = () => {
      this.activeSection = "general";
      this.display();
    };
    const clientsTab = navContainer.createEl("button", {
      text: "Clients",
      cls: this.activeSection === "clients" ? "smart-link-formatter-tab-active" : ""
    });
    clientsTab.onclick = () => {
      this.activeSection = "clients";
      this.display();
    };
    const overridesTab = navContainer.createEl("button", {
      text: "Overrides",
      cls: this.activeSection === "overrides" ? "smart-link-formatter-tab-active" : ""
    });
    overridesTab.onclick = () => {
      this.activeSection = "overrides";
      this.display();
    };
    containerEl.createEl("div", { cls: "smart-link-formatter-section-divider" });
    if (this.activeSection === "general") {
      this.displayGeneralSettings(containerEl);
    } else if (this.activeSection === "clients") {
      this.displayClientSettings(containerEl);
    } else if (this.activeSection === "overrides") {
      this.displayOverrideSettings(containerEl);
    }
  }
  displayGeneralSettings(containerEl) {
    new import_obsidian4.Setting(containerEl).setName("Auto-linking").setDesc("Automatically format links when pasting URLs, except when overriden.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoLink).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.autoLink = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian4.Setting(containerEl).setName("Failure mode").setDesc('What to do when a link fails to fetch. "Revert" pastes the original URL. "Alert" shows [Failed to fetch title](url).').addDropdown((dropdown) => dropdown.addOption(FailureMode.Revert, "Revert to plain URL").addOption(FailureMode.Alert, "Show failure message").setValue(this.plugin.settings.failureMode).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.failureMode = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian4.Setting(containerEl).setName("Fetch timeout").setDesc("Maximum time (in seconds) to wait for page metadata. (3-60s)").addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "3";
      text.inputEl.max = "60";
      text.inputEl.step = "1";
      text.setPlaceholder("10").setValue(String(this.plugin.settings.timeoutSeconds)).onChange((value) => __async(this, null, function* () {
        const numValue = parseInt(value);
        if (!isNaN(numValue) && numValue >= 3 && numValue <= 60) {
          this.plugin.settings.timeoutSeconds = numValue;
          yield this.plugin.saveSettings();
          text.inputEl.removeAttribute("aria-label");
        } else {
          text.inputEl.addClass("smart-link-formatter-invalid");
        }
      }));
    });
    new import_obsidian4.Setting(containerEl).setName("Replacements").setDesc("Apply regex find/replace transformations after formatting links. Patterns are applied in order.").setHeading();
    this.plugin.settings.titleReplacements.forEach((replacement, index) => {
      const setting = new import_obsidian4.Setting(containerEl).setClass("smart-link-formatter-replacement-setting");
      setting.addText((text) => text.setPlaceholder("Regex pattern").setValue(replacement.pattern).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.titleReplacements[index].pattern = value;
        yield this.plugin.saveSettings();
      })));
      setting.controlEl.createSpan({ text: " \u2192 ", cls: "smart-link-formatter-arrow" });
      setting.addText((text) => text.setPlaceholder("Replacement").setValue(replacement.replacement).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.titleReplacements[index].replacement = value;
        yield this.plugin.saveSettings();
      })));
      setting.addToggle((toggle) => toggle.setValue(replacement.enabled).setTooltip("Enable/disable this replacement").onChange((value) => __async(this, null, function* () {
        this.plugin.settings.titleReplacements[index].enabled = value;
        yield this.plugin.saveSettings();
      })));
      setting.addButton((button) => button.setIcon("arrow-up").setTooltip("Move up").setDisabled(index === 0).onClick(() => __async(this, null, function* () {
        const temp = this.plugin.settings.titleReplacements[index];
        this.plugin.settings.titleReplacements[index] = this.plugin.settings.titleReplacements[index - 1];
        this.plugin.settings.titleReplacements[index - 1] = temp;
        yield this.plugin.saveSettings();
        this.display();
      })));
      setting.addButton((button) => button.setIcon("arrow-down").setTooltip("Move down").setDisabled(index === this.plugin.settings.titleReplacements.length - 1).onClick(() => __async(this, null, function* () {
        const temp = this.plugin.settings.titleReplacements[index];
        this.plugin.settings.titleReplacements[index] = this.plugin.settings.titleReplacements[index + 1];
        this.plugin.settings.titleReplacements[index + 1] = temp;
        yield this.plugin.saveSettings();
        this.display();
      })));
      setting.addButton((button) => button.setIcon("trash").setTooltip("Delete replacement").onClick(() => __async(this, null, function* () {
        this.plugin.settings.titleReplacements.splice(index, 1);
        yield this.plugin.saveSettings();
        this.display();
      })));
    });
    new import_obsidian4.Setting(containerEl).addButton((button) => button.setButtonText("Add replacement rule").setCta().onClick(() => __async(this, null, function* () {
      this.plugin.settings.titleReplacements.push({
        pattern: "",
        replacement: "",
        enabled: true
      });
      yield this.plugin.saveSettings();
      this.display();
    })));
  }
  displayClientSettings(containerEl) {
    for (const client of CLIENTS) {
      const setting = new import_obsidian4.Setting(containerEl).setName(`${client.displayName} link format`).setClass("smart-link-formatter-tall-textarea-setting");
      setting.descEl.appendText("Available variables:");
      const ul = setting.descEl.createEl("ul");
      for (const v of client.getAvailableVariables()) {
        ul.createEl("li").createEl("code", { text: `{${v}}` });
      }
      const defaultTag = setting.descEl.createEl("span", { text: `Default: ` });
      defaultTag.createEl("code", { text: client.defaultFormat });
      setting.addTextArea((text) => text.setPlaceholder(client.defaultFormat).setValue(this.plugin.settings.clientFormats[client.name] || client.defaultFormat).then((textArea) => {
        textArea.inputEl.rows = 2;
        textArea.inputEl.addClass("smart-link-formatter-setting-textarea");
      }).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.clientFormats[client.name] = value;
        yield this.plugin.saveSettings();
      })));
    }
  }
  displayOverrideSettings(containerEl) {
    new import_obsidian4.Setting(containerEl).setName("Blacklisted domains").setDesc("Comma-separated list of domains that should never be auto-formatted. URLs from these domains will be pasted as-is.").addTextArea((text) => text.setPlaceholder("example.com, test.org").setValue(this.plugin.settings.blacklistedDomains).then((textArea) => {
      textArea.inputEl.rows = 4;
      textArea.inputEl.addClass("smart-link-formatter-setting-textarea");
    }).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.blacklistedDomains = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian4.Setting(containerEl).setName("Paste URL into selection").setDesc("Allows pasting a URL over selected text, which will allow other plugins or default behavior to handle it instead of auto-formatting.").addToggle((toggle) => toggle.setValue(this.plugin.settings.pasteIntoSelection).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.pasteIntoSelection = value;
      yield this.plugin.saveSettings();
    })));
  }
};

// src/main.ts
var import_obsidian6 = __toModule(require("obsidian"));
var BUFFER = "\u200B";
var generatePlaceholder = (placeholder) => {
  return placeholder + BUFFER;
};
var placeholderPattern = /<span class="link-loading" id="(link-placeholder-[^"]+)"(?:\s+url="([^"]*)")?>Loading\.\.\.<\/span>(?:\u200B+)?/g;
var SmartLinkFormatterPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.activePlaceholders = new Set();
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addSettingTab(new LinkFormatterSettingTab(this.app, this));
      this.registerEvent(this.app.workspace.on("editor-paste", (evt, editor) => {
        if (evt.defaultPrevented)
          return;
        void this.handlePaste(evt, editor);
      }));
      this.registerEvent(this.app.workspace.on("file-open", (file) => {
        if (file) {
          this.cleanupOrphanedPlaceholders();
        }
      }));
      this.addCommand({
        id: "format-link-at-cursor",
        name: "Format link at cursor",
        editorCallback: (editor) => {
          void this.formatLinkAtCursor(editor);
        }
      });
      this.addCommand({
        id: "format-all-links",
        name: "Format all links",
        editorCallback: (editor) => {
          this.formatAllLinks(editor);
        }
      });
      this.cleanupOrphanedPlaceholders();
    });
  }
  cleanupOrphanedPlaceholders() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
    if (!activeView || !activeView.editor)
      return;
    const editor = activeView.editor;
    const content = editor.getValue();
    const matches = content.matchAll(placeholderPattern);
    const orphanedMatches = [];
    for (const match of matches) {
      const fullMatch = match[0];
      if (!this.activePlaceholders.has(fullMatch) && match.index !== void 0) {
        orphanedMatches.push({ match, index: match.index });
      }
    }
    if (orphanedMatches.length === 0)
      return;
    for (let i = orphanedMatches.length - 1; i >= 0; i--) {
      const { match, index } = orphanedMatches[i];
      const fullMatch = match[0];
      const placeholderId = match[1];
      const url = match[2] || "";
      const inactivePlaceholder = `<span class="link-loading-inactive" id="${placeholderId}" url="${url}">Failed to resolve</span>`;
      const startPos = editor.offsetToPos(index);
      const endPos = editor.offsetToPos(index + fullMatch.length);
      editor.replaceRange(inactivePlaceholder, startPos, endPos);
    }
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
  handlePaste(evt, editor) {
    return __async(this, null, function* () {
      if (!this.settings.autoLink)
        return;
      if (!evt.clipboardData)
        return;
      const clipboardText = evt.clipboardData.getData("text/plain");
      const activeFile = this.app.workspace.getActiveFile();
      if (!activeFile)
        return;
      if (this.shouldOverride(editor))
        return;
      if (this.shouldReplace(editor, clipboardText)) {
        if (this.isBlacklisted(clipboardText))
          return;
        evt.preventDefault();
        void this.handleFormat(clipboardText, editor);
        return;
      }
      if (/https?:\/\//.test(clipboardText)) {
        const cursor = editor.getCursor();
        const allLines = editor.getValue().split("\n");
        if (isPositionProtected(allLines, cursor.line, cursor.ch))
          return;
        evt.preventDefault();
        const startLine = cursor.line;
        editor.replaceSelection(clipboardText);
        const endLine = editor.getCursor().line;
        this.formatLinksInRange(editor, startLine, endLine);
      }
    });
  }
  handleFormat(clipboardText, editor) {
    return __async(this, null, function* () {
      const token = generateUniqueToken(clipboardText);
      const placeholder = generatePlaceholder(token);
      this.activePlaceholders.add(placeholder);
      editor.replaceSelection(placeholder);
      const timeoutPromise = new Promise((_, reject) => window.setTimeout(() => reject(new Error("Fetch timeout")), this.settings.timeoutSeconds * 1e3));
      let didReplace = false;
      try {
        const normalized = normalizeUrl(clipboardText);
        const client = CLIENTS.find((client2) => client2.matches(normalized));
        if (client) {
          const metadata = yield Promise.race([
            client.fetchMetadata(clipboardText),
            timeoutPromise
          ]);
          const formattedText = unescapeHtml(client.format(metadata, clipboardText, this));
          didReplace = this.replacePlaceholder(placeholder, formattedText, editor);
        } else {
          throw new Error("No client found for link");
        }
      } catch (error) {
        console.error("Failed to format link:", error);
        new import_obsidian5.Notice("Failed to format link");
        const failureText = FailureMode.format(this.settings.failureMode, clipboardText);
        didReplace = this.replacePlaceholder(placeholder, failureText, editor);
      }
      if (!didReplace) {
        this.cleanupOrphanedPlaceholders();
      }
    });
  }
  shouldReplace(editor, text) {
    if (!isLink(text))
      return false;
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    if (editor.somethingSelected()) {
      return true;
    }
    const textBeforeCursor = line.substring(0, cursor.ch);
    const charAfterCursor = cursor.ch < line.length ? line[cursor.ch] : "";
    const potentialLinkMatch = textBeforeCursor.match(/\[.*?\]\($/);
    if (potentialLinkMatch && charAfterCursor === ")") {
      return false;
    }
    const allLines = editor.getValue().split("\n");
    return !isPositionProtected(allLines, cursor.line, cursor.ch);
  }
  shouldOverride(editor) {
    if (this.settings.pasteIntoSelection && editor.somethingSelected()) {
      return true;
    }
    return false;
  }
  isBlacklisted(text) {
    try {
      const url = new URL(text);
      const blacklist = this.settings.blacklistedDomains.split(",").map((domain) => domain.trim()).filter((domain) => domain.length > 0);
      if (blacklist.some((domain) => url.hostname.includes(domain))) {
        return true;
      }
    } catch (e) {
      console.error("Failed to parse URL for blacklist check:", e);
      return true;
    }
    return false;
  }
  replacePlaceholder(placeholder, newText, editor) {
    let didReplace = false;
    try {
      const editorContent = editor.getValue();
      if (editorContent.includes(placeholder)) {
        const startPos = editor.offsetToPos(editorContent.indexOf(placeholder));
        const endPos = editor.offsetToPos(editorContent.indexOf(placeholder) + placeholder.length);
        editor.replaceRange(newText, startPos, endPos);
        didReplace = true;
      } else {
        console.warn("Smart Link Formatter: Placeholder not found, inserting at cursor position.");
        editor.replaceSelection(newText);
        didReplace = true;
      }
    } catch (error) {
      console.error("Smart Link Formatter: Failed to replace placeholder.", error);
      new import_obsidian5.Notice("Error updating link in file.");
      didReplace = false;
    }
    this.activePlaceholders.delete(placeholder);
    return didReplace;
  }
  formatLinksInRange(editor, startLine, endLine) {
    const allLines = editor.getValue().split("\n");
    const urls = findUnformattedUrls(allLines, startLine, endLine).filter((u) => !this.isBlacklisted(u.url));
    for (const { url, line, start, end } of urls.reverse()) {
      editor.setSelection({ line, ch: start }, { line, ch: end });
      void this.handleFormat(url, editor);
    }
    return urls.length;
  }
  formatAllLinks(editor) {
    let startLine, endLine;
    if (editor.somethingSelected()) {
      startLine = editor.getCursor("from").line;
      endLine = editor.getCursor("to").line;
    } else {
      startLine = 0;
      endLine = editor.getValue().split("\n").length - 1;
    }
    const count = this.formatLinksInRange(editor, startLine, endLine);
    if (count === 0) {
      new import_obsidian5.Notice("No unformatted links found");
    } else {
      new import_obsidian5.Notice(`Formatting ${count} link${count > 1 ? "s" : ""}...`);
    }
  }
  formatLinkAtCursor(editor) {
    return __async(this, null, function* () {
      const cursor = editor.getCursor();
      const line = editor.getLine(cursor.line);
      const extraction = extractUrlAtCursor(line, cursor.ch);
      if (!extraction) {
        new import_obsidian5.Notice("No URL found at cursor position");
        return;
      }
      const { url, start, end } = extraction;
      if (this.isBlacklisted(url)) {
        new import_obsidian5.Notice("URL is in blacklisted domains");
        return;
      }
      const startPos = { line: cursor.line, ch: start };
      const endPos = { line: cursor.line, ch: end };
      editor.setSelection(startPos, endPos);
      void this.handleFormat(url, editor);
    });
  }
};
